language: node_js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
      - gcc-4.9
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.9 CC=gcc-4.9; fi
node_js:
  - '7'
  - '6'
  - '5'
  - '4'
  - '0.12'
  - '0.10'
os:
  - osx
  - linux
